Fixed Pref Window and view/remove button
OpenIntelWireless/HeliPort pull request #253
Opened 2024-07-02 03:29 UTC by IVORRY

Fixed the Pref Window and the view/remove button that were not working in version 1.5.0 Alpha.

2024-07-02 08:04 UTC, williambj1 requested changes
Thanks for the PR! Please address each comment and remove unnecessary changes (newlines, trailing whitespaces).

2024-07-03 10:40 UTC, williambj1 requested changes

2024-07-03 10:40 UTC, williambj1 commented on HeliPort/Appearance/StatusMenu.swift
> +            }
Would be better to lazy initialize `preferenceWindow` as a non optional

2024-07-03 23:13 UTC, IVORRY commented
Good to go

2024-07-04 00:52 UTC, williambj1 approved these changes

2024-07-04 00:52 UTC, merged